name: CD - Continuous Delivery
on:
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "Verificação de CD concluída com sucesso!"
